import type { MiscIntegrationDefinition, MiscIntegrationId } from "@/lib/integrations/types";

export type { MiscIntegrationDefinition, MiscIntegrationId } from "@/lib/integrations/types";
export type { MiscCatalogFilter, MiscIntegrationCategory } from "@/lib/integrations/types";

/** Static misc integrations — no device app scan on any platform. */
export const MISC_INTEGRATIONS_CATALOG: readonly MiscIntegrationDefinition[] = [
  {
    id: "dropbox",
    name: "Dropbox",
    category: "work",
    icon: "dropbox",
    iosScheme: "dbapi-8",
    appSchemeUrls: ["dbapi-8://", "dbapi-2://", "dropbox://"],
    website: "https://www.dropbox.com/",
    iosStoreUrl: "https://apps.apple.com/app/dropbox/id327507135",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.dropbox.android",
  },
  {
    id: "google_drive",
    name: "Google Drive",
    category: "work",
    icon: "google-drive",
    iosScheme: "googledrive",
    appSchemeUrls: ["googledrive://", "com.google.Drive://"],
    website: "https://drive.google.com/",
    iosStoreUrl: "https://apps.apple.com/app/google-drive/id507874739",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.google.android.apps.docs",
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "work",
    icon: "gmail",
    iosScheme: "googlegmail",
    appSchemeUrls: ["googlegmail://", "gmail://"],
    website: "https://mail.google.com/",
    iosStoreUrl: "https://apps.apple.com/app/gmail-email-by-google/id422689480",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.google.android.gm",
  },
  {
    id: "google_maps",
    name: "Google Maps",
    category: "work",
    icon: "google-maps",
    iosScheme: "comgooglemaps",
    appSchemeUrls: ["comgooglemaps://", "googlemaps://"],
    website: "https://www.google.com/maps",
    iosStoreUrl: "https://apps.apple.com/app/google-maps/id585027354",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.google.android.apps.maps",
  },
  {
    id: "waze",
    name: "Waze",
    category: "work",
    icon: "waze",
    iosScheme: "waze",
    appSchemeUrls: ["waze://"],
    website: "https://www.waze.com/",
    iosStoreUrl: "https://apps.apple.com/app/waze-navigation-live-traffic/id323229106",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.waze",
  },
  {
    id: "slack",
    name: "Slack",
    category: "work",
    icon: "slack",
    iosScheme: "slack",
    appSchemeUrls: ["slack://"],
    website: "https://slack.com/",
    iosStoreUrl: "https://apps.apple.com/app/slack/id618783545",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.Slack",
  },
  {
    id: "microsoft_teams",
    name: "Microsoft Teams",
    category: "work",
    icon: "microsoft-teams",
    iosScheme: "msteams",
    appSchemeUrls: ["msteams://"],
    website: "https://www.microsoft.com/microsoft-teams/",
    iosStoreUrl: "https://apps.apple.com/app/microsoft-teams/id1113153706",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.microsoft.teams",
  },
  {
    id: "outlook",
    name: "Outlook",
    category: "work",
    icon: "microsoft-outlook",
    iosScheme: "ms-outlook",
    appSchemeUrls: ["ms-outlook://", "ms-outlook-shared://"],
    website: "https://www.microsoft.com/microsoft-365/outlook-email-calendar",
    iosStoreUrl: "https://apps.apple.com/app/microsoft-outlook/id951937596",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.microsoft.office.outlook",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    category: "work",
    icon: "microsoft-onedrive",
    iosScheme: "onedrive",
    appSchemeUrls: ["onedrive://", "ms-onedrive://"],
    website: "https://www.microsoft.com/microsoft-365/onedrive/online-cloud-storage",
    iosStoreUrl: "https://apps.apple.com/app/microsoft-onedrive/id477537958",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.microsoft.skydrive",
  },
  {
    id: "box",
    name: "Box",
    category: "work",
    icon: "box",
    iosScheme: "box",
    appSchemeUrls: ["box://", "boxapp://"],
    website: "https://www.box.com/",
    iosStoreUrl: "https://apps.apple.com/app/box-cloud-storage/id290853822",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.box.android",
  },
  {
    id: "apple_maps",
    name: "Apple Maps",
    category: "work",
    icon: "apple",
    iosScheme: "maps",
    appSchemeUrls: ["maps://", "http://maps.apple.com/"],
    website: "https://maps.apple.com/",
    iosStoreUrl: "https://apps.apple.com/app/apple-maps/id915056765",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.apple.android.maps",
  },
  {
    id: "zoom",
    name: "Zoom",
    category: "work",
    icon: "video",
    iosScheme: "zoomus",
    appSchemeUrls: ["zoomus://"],
    website: "https://zoom.us/",
    iosStoreUrl: "https://apps.apple.com/app/zoom-one-platform/id546505307",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=us.zoom.videomeetings",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    category: "work",
    icon: "calculator-variant",
    iosScheme: "intuitqb",
    appSchemeUrls: ["intuitqb://", "com.intuit.quickbooks://"],
    website: "https://quickbooks.intuit.com/",
    iosStoreUrl: "https://apps.apple.com/app/quickbooks-accounting/id584606479",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.intuit.quickbooks",
  },
  {
    id: "procore",
    name: "Procore",
    category: "work",
    icon: "hammer",
    iosScheme: "procore",
    appSchemeUrls: ["procore://"],
    website: "https://www.procore.com/",
    iosStoreUrl: "https://apps.apple.com/app/procore/id314642050",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.procore.activities",
  },
  {
    id: "companycam",
    name: "CompanyCam",
    category: "work",
    icon: "camera",
    iosScheme: "companycam",
    appSchemeUrls: ["companycam://"],
    website: "https://companycam.com/",
    iosStoreUrl: "https://apps.apple.com/app/companycam/id1450016691",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.companycam.companycam",
  },
  {
    id: "buildertrend",
    name: "Buildertrend",
    category: "work",
    icon: "home-account",
    iosScheme: "buildertrend",
    appSchemeUrls: ["buildertrend://"],
    website: "https://buildertrend.com/",
    iosStoreUrl: "https://apps.apple.com/app/buildertrend/id1037510788",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.buildertrend.buildertrend",
  },
  {
    id: "jobber",
    name: "Jobber",
    category: "work",
    icon: "briefcase-outline",
    iosScheme: "jobber",
    appSchemeUrls: ["jobber://"],
    website: "https://getjobber.com/",
    iosStoreUrl: "https://apps.apple.com/app/jobber/id1071421261",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.getjobber.jobber",
  },
  {
    id: "servicetitan",
    name: "ServiceTitan",
    category: "work",
    icon: "wrench",
    iosScheme: "servicetitan",
    appSchemeUrls: ["servicetitan://"],
    website: "https://www.servicetitan.com/",
    iosStoreUrl: "https://apps.apple.com/app/servicetitan/id1203126458",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.servicetitan.mobile",
  },
  {
    id: "fieldwire",
    name: "Fieldwire",
    category: "work",
    icon: "clipboard-check-outline",
    iosScheme: "fieldwire",
    appSchemeUrls: ["fieldwire://"],
    website: "https://www.fieldwire.com/",
    iosStoreUrl: "https://apps.apple.com/app/fieldwire/id780165517",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.fieldwire.android",
  },
  {
    id: "asana",
    name: "Asana",
    category: "work",
    icon: "checkbox-marked-circle-outline",
    iosScheme: "asana",
    appSchemeUrls: ["asana://"],
    website: "https://asana.com/",
    iosStoreUrl: "https://apps.apple.com/app/asana/id489969512",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.asana.app",
  },
  {
    id: "trello",
    name: "Trello",
    category: "work",
    icon: "view-column",
    iosScheme: "trello",
    appSchemeUrls: ["trello://"],
    website: "https://trello.com/",
    iosStoreUrl: "https://apps.apple.com/app/trello/id327135242",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.trello",
  },
  {
    id: "notion",
    name: "Notion",
    category: "work",
    icon: "notebook-outline",
    iosScheme: "notion",
    appSchemeUrls: ["notion://"],
    website: "https://www.notion.so/",
    iosStoreUrl: "https://apps.apple.com/app/notion/id1232780281",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=notion.id",
  },
  {
    id: "smartsheet",
    name: "Smartsheet",
    category: "work",
    icon: "table",
    iosScheme: "smartsheet",
    appSchemeUrls: ["smartsheet://"],
    website: "https://www.smartsheet.com/",
    iosStoreUrl: "https://apps.apple.com/app/smartsheet/id623369782",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.smartsheet.android",
  },
  {
    id: "docusign",
    name: "DocuSign",
    category: "work",
    icon: "file-sign",
    iosScheme: "docusign",
    appSchemeUrls: ["docusign://", "docusignit://"],
    website: "https://www.docusign.com/",
    iosStoreUrl: "https://apps.apple.com/app/docusign/id336800266",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.docusign.esign",
  },
  {
    id: "adobe_acrobat",
    name: "Adobe Acrobat",
    category: "work",
    icon: "file-pdf-box",
    iosScheme: "acrobat",
    appSchemeUrls: ["acrobat://", "adobereader://"],
    website: "https://www.adobe.com/acrobat/mobile.html",
    iosStoreUrl: "https://apps.apple.com/app/adobe-acrobat-reader/id469337564",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.adobe.reader",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "work",
    icon: "hubspot",
    iosScheme: "hubspot",
    appSchemeUrls: ["hubspot://"],
    website: "https://www.hubspot.com/",
    iosStoreUrl: "https://apps.apple.com/app/hubspot/id1102355471",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.hubspot.android",
  },
  {
    id: "ringcentral",
    name: "RingCentral",
    category: "work",
    icon: "phone",
    iosScheme: "ringcentral",
    appSchemeUrls: ["ringcentral://", "rcmobile://"],
    website: "https://www.ringcentral.com/",
    iosStoreUrl: "https://apps.apple.com/app/ringcentral/id659718043",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.ringcentral.android",
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    category: "work",
    icon: "calendar",
    iosScheme: "googlecalendar",
    appSchemeUrls: ["googlecalendar://", "com.google.calendar://"],
    website: "https://calendar.google.com/",
    iosStoreUrl: "https://apps.apple.com/app/google-calendar/id909819836",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.google.android.calendar",
  },
  {
    id: "evernote",
    name: "Evernote",
    category: "work",
    icon: "elephant",
    iosScheme: "evernote",
    appSchemeUrls: ["evernote://"],
    website: "https://evernote.com/",
    iosStoreUrl: "https://apps.apple.com/app/evernote/id281796108",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.evernote",
  },
  {
    id: "roblox",
    name: "Roblox",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "roblox",
    appSchemeUrls: ["roblox://"],
    website: "https://www.roblox.com/",
    iosStoreUrl: "https://apps.apple.com/app/roblox/id431946152",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.roblox.client",
  },
  {
    id: "minecraft",
    name: "Minecraft",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "minecraft",
    appSchemeUrls: ["minecraft://"],
    website: "https://www.minecraft.net/",
    iosStoreUrl: "https://apps.apple.com/app/minecraft/id479516143",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.mojang.minecraftpe",
  },
  {
    id: "clash_of_clans",
    name: "Clash of Clans",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "clashofclans",
    appSchemeUrls: ["clashofclans://"],
    website: "https://supercell.com/en/games/clashofclans/",
    iosStoreUrl: "https://apps.apple.com/app/clash-of-clans/id529479190",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.supercell.clashofclans",
  },
  {
    id: "candy_crush",
    name: "Candy Crush Saga",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "candycrushsaga",
    appSchemeUrls: ["candycrushsaga://"],
    website: "https://www.king.com/game/candycrush/",
    iosStoreUrl: "https://apps.apple.com/app/candy-crush-saga/id553834731",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.king.candycrushsaga",
  },
  {
    id: "call_of_duty_mobile",
    name: "Call of Duty Mobile",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "codmobile",
    appSchemeUrls: ["codmobile://", "callofduty://"],
    website: "https://www.callofduty.com/mobile",
    iosStoreUrl: "https://apps.apple.com/app/call-of-duty-mobile/id1287282214",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter",
  },
  {
    id: "pubg_mobile",
    name: "PUBG Mobile",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "pubgmobile",
    appSchemeUrls: ["pubgmobile://"],
    website: "https://www.pubgmobile.com/",
    iosStoreUrl: "https://apps.apple.com/app/pubg-mobile/id1330123889",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.tencent.ig",
  },
  {
    id: "fortnite",
    name: "Fortnite",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "fortnite",
    appSchemeUrls: ["fortnite://"],
    website: "https://www.fortnite.com/",
    iosStoreUrl: "https://apps.apple.com/app/fortnite/id1261357853",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.epicgames.fortnite",
  },
  {
    id: "xbox",
    name: "Xbox",
    category: "games",
    icon: "microsoft-xbox",
    iosScheme: "xbox",
    appSchemeUrls: ["xbox://", "xboxapp://"],
    website: "https://www.xbox.com/",
    iosStoreUrl: "https://apps.apple.com/app/xbox/id736179781",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.microsoft.xboxone.smartglass",
  },
  {
    id: "playstation",
    name: "PlayStation App",
    category: "games",
    icon: "sony-playstation",
    iosScheme: "playstation",
    appSchemeUrls: ["playstation://", "psapp://"],
    website: "https://www.playstation.com/",
    iosStoreUrl: "https://apps.apple.com/app/playstation-app/id410896080",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.scee.psxandroid",
  },
  {
    id: "steam_link",
    name: "Steam Link",
    category: "games",
    icon: "steam",
    iosScheme: "steamlink",
    appSchemeUrls: ["steamlink://", "steam://"],
    website: "https://store.steampowered.com/app/353380/Steam_Link/",
    iosStoreUrl: "https://apps.apple.com/app/steam-link/id1246969117",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.valvesoftware.steamlink",
  },
  {
    id: "pokemon_go",
    name: "Pokémon GO",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "pokemongo",
    appSchemeUrls: ["pokemongo://"],
    website: "https://pokemongolive.com/",
    iosStoreUrl: "https://apps.apple.com/app/pokemon-go/id1094591345",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo",
  },
  {
    id: "among_us",
    name: "Among Us",
    category: "games",
    icon: "gamepad-variant",
    iosScheme: "amongus",
    appSchemeUrls: ["amongus://", "innersloth://"],
    website: "https://www.innersloth.com/games/among-us/",
    iosStoreUrl: "https://apps.apple.com/app/among-us/id1351168404",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.innersloth.spacemafia",
  },
] as const;

export function miscIntegrationById(id: string): MiscIntegrationDefinition | undefined {
  return MISC_INTEGRATIONS_CATALOG.find((e) => e.id === id);
}

export function miscIntegrationIds(): MiscIntegrationId[] {
  return MISC_INTEGRATIONS_CATALOG.map((e) => e.id);
}

/** Schemes for iOS Info.plist (deduped, lowercase). */
export function miscIntegrationQuerySchemes(): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const def of MISC_INTEGRATIONS_CATALOG) {
    const candidates = [def.iosScheme, ...def.appSchemeUrls.map((u) => u.replace(/:\/\/.*$/, ""))];
    for (const raw of candidates) {
      const scheme = raw.replace(/:\/\//g, "").replace(/:$/g, "").trim().toLowerCase();
      if (!scheme || seen.has(scheme)) continue;
      seen.add(scheme);
      out.push(scheme);
    }
  }
  return out;
}
