import type { MiscIntegrationId } from "@/lib/integrations/types";

/** Known Android package names for misc integrations (no launcher scan). */
export const MISC_ANDROID_PACKAGES: Partial<Record<MiscIntegrationId, string>> = {
  dropbox: "com.dropbox.android",
  google_drive: "com.google.android.apps.docs",
  gmail: "com.google.android.gm",
  google_maps: "com.google.android.apps.maps",
  waze: "com.waze",
  slack: "com.Slack",
  microsoft_teams: "com.microsoft.teams",
  outlook: "com.microsoft.office.outlook",
  onedrive: "com.microsoft.skydrive",
  box: "com.box.android",
  apple_maps: "com.apple.android.maps",
  zoom: "us.zoom.videomeetings",
  quickbooks: "com.intuit.quickbooks",
  procore: "com.procore.activities",
  companycam: "com.companycam.companycam",
  buildertrend: "com.buildertrend.buildertrend",
  jobber: "com.getjobber.jobber",
  servicetitan: "com.servicetitan.mobile",
  fieldwire: "com.fieldwire.android",
  asana: "com.asana.app",
  trello: "com.trello",
  notion: "notion.id",
  smartsheet: "com.smartsheet.android",
  docusign: "com.docusign.esign",
  adobe_acrobat: "com.adobe.reader",
  hubspot: "com.hubspot.android",
  ringcentral: "com.ringcentral.android",
  google_calendar: "com.google.android.calendar",
  evernote: "com.evernote",
  roblox: "com.roblox.client",
  minecraft: "com.mojang.minecraftpe",
  clash_of_clans: "com.supercell.clashofclans",
  candy_crush: "com.king.candycrushsaga",
  call_of_duty_mobile: "com.activision.callofduty.shooter",
  pubg_mobile: "com.tencent.ig",
  fortnite: "com.epicgames.fortnite",
  xbox: "com.microsoft.xboxone.smartglass",
  playstation: "com.scee.psxandroid",
  steam_link: "com.valvesoftware.steamlink",
  pokemon_go: "com.nianticlabs.pokemongo",
  among_us: "com.innersloth.spacemafia",
};
