/** @deprecated Import from `@/lib/subscription/featureAccess` — thin re-export for legacy paths. */
export {
  SUBSCRIPTION_SETTINGS_HREF,
  canAccessFeature,
  canUseFeature,
  featureGateAlertTitle,
  featureGateMessage,
  filterMaterialsSearchTilesForTier,
  getHomeTileGatedFeature,
  getRequiredTier,
  getUpgradeTarget,
  hasFeature,
  homeJobFolderHrefForTier,
  isBossTier,
  isBossmanTier,
  isProTier,
  isSuperBossmanTier,
  isSupplyHouseAllowedForTier,
  promptUpgradeForFeature,
  promptUpgradeForHomeTile,
  promptUpgradeForHomeTileWhenReady,
  requireBoss,
  requireFeature,
  requirePro,
  type FeatureAccessContext,
  type FeatureKey,
  type GatedFeature,
  type HomeMenuTileKey,
} from "@/lib/subscription/featureAccess";
