/**
 * Subscription tier definitions — re-exported from `lib/subscriptions/tiers.ts`.
 * RevenueCat mapping: docs/SUBSCRIPTION_TIERS.md
 */

export {
  AI_ADDON_PACKS,
  BOSSMAN_SUPPLY_HOUSE_PRESET_IDS,
  HELPER_TRIAL_DAYS,
  IDEAL_SOLUTIONS_PRO_ENTITLEMENT,
  LEGACY_BOSS_MAN_MONTHLY_PACKAGE_IDS,
  LEGACY_BOSS_MAN_MONTHLY_PRODUCT_IDS,
  LEGACY_ENTITLEMENT_IDS,
  LEGACY_TIER_PACKAGE_IDS,
  LEGACY_TIER_PRODUCT_IDS,
  PAID_TIER_IDS,
  PLAN_PICKER_FAIR_USE_NOTE,
  PLAN_PICKER_HEADLINE,
  RETAIL_MATERIAL_SUPPLIER_IDS,
  SUBSCRIPTION_PLANS,
  SUBSCRIPTION_TIER_CONFIG,
  SUBSCRIPTION_TIER_ORDER,
  TRIAL_AI_REQUESTS_TOTAL,
  TRIAL_DAYS,
  dailyAiLimitForTier,
  dailyImageUploadLimitForTier,
  getSubscriptionPlan,
  getTierConfig,
  highestTierFromKeys,
  isEmployeeEligibleTier,
  isPaidSubscriptionTier,
  logTierDebug,
  maxEmployeesForTier,
  monthlyAiLimitForTier,
  normalizeSubscriptionTierId,
  paidSubscriptionPlans,
  paidTierConfigs,
  plansForPaywall,
  plansForSubscriptionScreen,
  resolveTierFromEntitlementKey,
  resolveTierFromProductId,
  tierMeetsMinimum,
  tierRank,
  type AiAddonPack,
  type AiAddonPackId,
  type LegacySubscriptionTierId,
  type PaidSubscriptionTierId,
  type SubscriptionPlan,
  type SubscriptionTierConfig,
  type SubscriptionTierId,
  type TierDebugSnapshot,
} from "@/lib/subscription/tiers";
